
---

- name: "Build container with ansible"

  hosts: localhost

  tasks:

  - name: stop running container

    command: docker stop anaibia-container
    ignore_errors: yes


  - name: remove stopped container

    command: docker rm anaibia-container

    ignore_errors: yes

  

  - name: remove used image

    command: docker rmi anaibia-img
    
    ignore_errors: yes
  


  - name: build docker image from dockerfile

    command: docker build -t cv-img .   


  - name: create tag to image
    
    command: docker tag cv-img kadhem-img


  - name: run container from image
    
    command:docker run -d --name anaibia-container -p 8094:80 anaibia-img
